---

# Before running this playbook: Create Backup-Partition

- name: Install rssh
  apt:
    name: rssh
    state: present

- name: Create duplicity user
  user:
    name: duplicity
    state: present
    password: '!'
    home: /var/lib/duplicity
    shell: /usr/bin/rssh
    createhome: yes

- name: Create shutdown user
  user:
    name: shutdown
    state: present
    password: '!'
    home: /var/lib/shutdown
    shell: "/usr/bin/shutdown -h now" # Is this sane?
    createhome: yes

- name: Mount Partition
  mount:
    src: "/dev/vg-wikipedia/backup"
    path: "/mnt/backup"
    state: mounted

- name: setup rights for backupfolder
  file:
    state: directory
    dest: "/mnt/backup"
    owner: "duplicity"
    mode: 0700

- name: copy ssh-pubkey
  authorized_key:
    user: duplicity
    state: present
    exclusive: yes
    key: "{{ lookup('file', 'duplicity.pub') }}"
    key_options: 'no-port-forwarding,no-x11-forwarding,no-agent-forwarding'

- name: copy ssh-pubkey for shutdown-user
  authorized_key:
    user: shutdown
    state: present
    exclusive: yes
    key: "{{ lookup('file', 'duplicity.pub') }}"
    key_options: 'command="sudo shutdown -h now",no-port-forwarding,no-x11-forwarding,no-agent-forwarding'

- name: Configure sudo-shutdown
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^(duplicity|shutdown)'
    line: 'shutdown ALL=(ALL) NOPASSWD: /usr/bin/shutdown -h now'
