---
- name: Install Java
  apt: name={{ item }} state=present default_release=buster-backports
  with_items:
    - openjdk-8-jre

- name: Create folder for java-apps
  file:
    path=/opt/java
    state=directory

- name: Install Pattypan
  get_url:
    url: https://github.com/yarl/pattypan/releases/download/v0.5.0/pattypan.jar
    dest: /opt/java/

- name: Install Commonist
  get_url:
    url: https://djini.de/commonist/commonist-1.10.0.zip
    dest: /opt/java/

- name: Download Vicuña
  get_url:
    url: https://github.com/yarl/vicuna/releases/download/1.23/vicuna-1.23.zip
    dest: /tmp/
      
- name: Unpack Vicuña
  unarchive:
    src: /tmp/vicuna-1.23.zip
    dest: /tmp
    remote_src: yes

- name: Install Vicuña
  copy:
    src: /tmp/vicuna-1.23/vicuna.jar
    dest: /opt/java/vicuna.jar
    remote_src: yes

- name: Download Imker
  get_url:
    url: https://github.com/MarcoFalke/wiki-java-tools/releases/download/v16.09.11-imker/Imker_v16.09.11.zip
    dest: /tmp/
      
- name: Unpack & Install Imker
  unarchive:
    src: /tmp/Imker_v16.09.11.zip
    dest: /opt/java/
    remote_src: yes
    exclude: run-imker-gui.exe

- name: Install .dektop-files for Vicuña, Commonist, Imker and Pattypan
  synchronize:
    src: wikijavaapps/desktop/
    dest: /usr/share/applications/

- name: Install icons for Vicuña, Commonist, Imker and Pattypan
  synchronize:
    src: wikijavaapps/pixmaps/
    dest: /usr/share/pixmaps/
