---
- name: Update apt cache
  apt: update_cache=yes

- name: Install anacron
  apt: name=anacron state=present

- name: Configure anacron
  copy: src=etc/anacrontab
        dest=/etc/anacrontab

- name: Install software for administrative use
  apt: name={{ item }} state=present
  with_items:
    - mosh
    - screen
    - htop
    - vim
    - strace
    - iotop
    - ldnsutils
    - rsync
    - perl
    - ntpdate
    - git
    - keepassx
    - python3-pip
    - ipython3

- name: Install Desktop
  apt: name={{ item }} state=present
  with_items:
    - lxde
    - xfce4
    - xfce4-goodies
    - lightdm
    - xdg-utils
    - firmware-linux-nonfree
    - ttf-mscorefonts-installer
    - fonts-noto
    - ttf-liberation
    - ttf-dejavu
    - fonts-hanazono

- name: Deinstall xscreensaver
  apt: name={{ item }} state=absent
  with_items:
    - xscreensaver
    - xscreensaver-data

- name: Install Office & spell checker
  apt: name={{ item }} state=present
  with_items:
    - libreoffice
    - libreoffice-gtk
    - libreoffice-l10n-de
    - libreoffice-help-de
    - hunspell-de-de
    - hunspell-en-us
    - hunspell-fr-modern
    - aspell-en
    - aspell-de
    - hyphen-en-us
    - hyphen-de
    - mythes-de
    - calibre
    - geany
    - meld

- name: Install PDF-Software
  apt: name={{ item }} state=present
  with_items:
    - cups-pdf
    - evince-gtk
    - okular
    - mupdf

- name: Install graphic applications
  apt: 
    name: "{{ item }}"
    state: latest
    default_release: "{{ansible_distribution_release}}-backports"
  with_items:
    - gimp
    - krita
    - xsane
    - imagemagick
    - inkscape
    - hugin
    - rawtherapee
    - darktable
  tags: 
    - imagesoftware

- name: Install browser
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - iceweasel
      #  - firefox
    - iceweasel-l10n-de
  ignore_errors: true

- name: Install multimedia applications
  apt: name={{ item }} state=present
  with_items:
    - vlc
    - mpv

- name: Install Java
  apt: name={{ item }} state=present default_release=jessie-backports
  with_items:
    - openjdk-8-jre

- name: Create folder for java-apps
  file:
    path=/opt/java
    state=directory

- name: Install various Wikipedia specific java-apps (1/3)
  synchronize:
    src=wikijavaapps/desktop/
    dest=/usr/share/applications/

- name: Install various Wikipedia specific java-apps (2/3)
  synchronize:
    src=wikijavaapps/jar/
    dest=/opt/java/

- name: Install various Wikipedia specific java-apps (3/3)
  synchronize:
    src=wikijavaapps/pixmaps/
    dest=/usr/share/pixmaps/

- name: Install winehq
  apt:
    name={{ item }}
    state=absent
  with_items:
    - wine
    - wine32
