---
- name: Update apt cache
  apt: update_cache=yes

- name: Install anacron
  apt: name=anacron state=present

- name: Configure anacron
  copy: src=etc/anacrontab
        dest=/etc/anacrontab

- name: Install software for administrative use
  apt: name={{ item }} state=present
  with_items:
    - mosh
    - screen
    - htop
    - vim
    - strace
    - iotop
    - ldnsutils
    - rsync
    - perl
    - ntpdate
    - git
    - python3-pip
    - ipython3
    - gnuplot

- include: desktop.yml
  tags: [desktop]

- include: usersoftware.yml
  tags: [usersoftware]

- include: javasoftware.yml
  tags: [java, javasoftware]

- name: Uninstall winehq
  apt:
    name={{ item }}
    state=absent
  with_items:
    - wine
    - wine32
