---
- name: WikiMUC
  hosts: debian_clients

  roles:
    - { role: base, tags: [ 'base' ] }
    - { role: software, tags: [ 'software' ] }
    - { role: useraccounts, tags: [ 'useraccounts' ] }
    - { role: scanner, tags: [ 'scanner' ] }
    - { role: ipsec, tags: [ 'ipsec' ] }
    - { role: artwork, tags: [ 'artwork' ] }
#    - { role: backupdest, tags: [ 'backupdest' ] }
