---
- name: Jimbo
  hosts: jimbo

  roles:
    - { role: watchdog, tags: [ 'watchdog' ] }
    - { role: zram, tags: [ 'zram' ] }
    - { role: smarthost, tags: [ 'smarthost' ] }

- name: WikiMUC
  hosts: debian_clients

  roles:
    - { role: base, tags: [ 'base' ] }
    - { role: software, tags: [ 'software' ] }
    - { role: useraccounts, tags: [ 'useraccounts' ] }
    - { role: scanner, tags: [ 'scanner' ] }
    - { role: ipsec, tags: [ 'ipsec' ] }
    - { role: artwork, tags: [ 'artwork' ] }
    - { role: monitoring, tags: [ 'monitoring', 'munin'] }
#    - { role: backupdest, tags: [ 'backupdest' ] }
