---
- name: Install plymouth
  apt:
    name: plymouth
    state: present

- name: Copy Wikimuc-theme
  rsync:
    src: usr/share/plymouth/themes/wikimuc
    dest: usr/share/plymouth/themes/wikimuc
  register: plymouth

- name: Change resolution of grub
  lineinfile:
    path: /etc/default/grub
    regexp: '#?GRUB_GFXMODE='
    line: 'GRUB_GFXMODE=1024x768'
  register: grubconf

- name: Enable splash
  replace:
    path: /etc/default/grub
    regexp: '#?GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 quiet splash"'
  register: grubconf

- name: Update grub config
  command: update-grub2
  when: grubconf.changed

- name: Enable plymouth-theme
  command: plymouth-set-default-theme wikimuc
  register: plymouth

- name: Update initramfs
  command: plymouth-set-default-theme --rebuild-initrd
  when: plymouth.changed
