---
- name: Install plymouth
  apt:
    name: plymouth
    state: present

- name: Install plymouth-themes
  apt:
    name: plymouth-themes
    state: present

- name: Copy Wikimuc-theme
  synchronize:
    src: usr/share/plymouth/themes/wikimuc
    dest: /usr/share/plymouth/themes/
  register: plymouth

- name: Change resolution of grub
  lineinfile:
    dest: /etc/default/grub
    regexp: '#?GRUB_GFXMODE='
    line: 'GRUB_GFXMODE=1280x1024'
  register: grubconf
  when: ansible_hostname != 'fasanerie'
  tags:
          - grub

- name: Enable splash
  replace:
    dest: /etc/default/grub
    regexp: '#?GRUB_CMDLINE_LINUX_DEFAULT="(.+?)( quiet splash)*"'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 quiet splash"'
  register: grubconf
  tags:
          - grub

- name: Fixup grub
  replace:
    dest: /etc/default/grub
    regexp: '( quiet| splash)+'
    replace: ' quiet splash"'
  register: grubconf
  tags:
          - grub

- name: Update grub config
  command: update-grub2
  when: grubconf.changed
          - grub

- name: Enable plymouth-theme
  command: plymouth-set-default-theme wikimuc
  register: plymouth

- name: Update initramfs
  command: plymouth-set-default-theme --rebuild-initrd wikimuc
  when: plymouth.changed
