---
- hosts: tivoli

  tasks:

    - name: Create user 'backup'
      user:
        name: backup
        #shell: /bin/false

    - name: Create Mountpoint-Folder
      file:
        path: /mnt/backup
        state: directory
        owner: backup

    - name: Add ssh-key to backup-user
      authorized_key:
        user: backup
        key: "{{ lookup('file', '~pi/.ssh/id_ed25519.pub')  }}"

    - name: Mount Backup-Partition
      mount: 
        src: /dev/vg-wikipedia/backup
        name: /mnt/backup
        fstype: ext4
        state: present

    - name: Do Backup
      local_action: shell SIGN_PASSPHRASE="" PASSPHRASE="" duplicity --encrypt-key 6D3CC613 --sign-key E26B02BB --ssh-backend pexpect /mnt/share/ scp://backup@tivoli//mnt/backup

    - name: Unmount Backup-Partition
      mount: 
        src: /dev/vg-wikipedia/backup
        name: /mnt/backup
        fstype: ext4
        state: unmounted

