---

# - name: Update apt cache
# apt: update_cache=yes

- name: Install memtest86
  apt: name=memtest86 state=present

- name: Add grub super-user
  blockinfile:
    dest: /etc/grub.d/40_custom
    block: |
      set superusers="root"
      password_pbkdf2 root grub.pbkdf2.sha512.10000.B14E923CE8B3E1972B270E8B7518B9BF9C156DA782469553CB48C86AA062CAA1CBECD17CCC810EC3FFB3CDBE0D2ED8D8D802D82C4F7E08CA23CBF9B96F2911E3.95F2F4EF95CD4E1856190EB7BDD6B78F4B8641650BCE1A400498C72B286BFE2B9E280513FCFC8DC57CB228613621E13CF4F0CB5C49B5904BAFB7B7A664BFDFCB

- name: Set unrestricted as default behavior for linux
  replace:
    dest: /etc/grub.d/10_linux
    regexp: '(grub_quote..) (\$\{CLASS} \\\$menuentry_id_option)'
    replace: '\1 --unrestricted \2'

- name: Set unrestricted as default behavior for windows
  replace:
    dest: /etc/grub.d/10_linux
    regexp: '(grub_quote..) (--class windows --class os)'
    replace: '\1 --unrestricted \2'
  when: ansible_hostname == 'fasanerie'

- name: Set timeout
  lineinfile:
    dest: /etc/default/grub
    regexp: 'GRUB_TIMEOUT=[0-9]*'
    line: 'GRUB_TIMEOUT=1'
  when: ansible_hostname != 'fasanerie'

- name: Set timeout
  lineinfile:
    dest: /etc/default/grub
    regexp: 'GRUB_TIMEOUT=[0-9]*'
    line: 'GRUB_TIMEOUT=3'
  when: ansible_hostname == 'fasanerie'

- name: Set graphics-resolution for Grub
  lineinfile:
    dest: /etc/default/grub
    regexp: 'GRUB_GFXPAYLOAD_LINUX=.*'
    line: 'GRUB_GFXPAYLOAD_LINUX=1920x1080'
  when: ansible_hostname == 'fasanerie'

- name: Set graphics-resolution for the fb
  lineinfile:
    dest: /etc/default/grub
    regexp: 'GRUB_GFXMODE=.*'
    line: 'GRUB_GFXMODE=1920x1080'
  when: ansible_hostname == 'fasanerie'

- name: Update Grub-config
  command: grub-mkconfig -o /boot/grub/grub.cfg # why not update-grub2?
