---
- include: apt-repos.yml
  tags:
    - apt
    - repos
- include: apt-cacher-client.yml
  tags: 
    - apt
    - repos
    - aptcacher
- include: filesystem.yml
  tags:
    - filesystem
#- include: pam_namespace.yml
#  tags:
#    - pam
#    - security
- include: unattendedupdates.yml
  tags:
    - unattendedupdates
- include: grub.yml
  tags:
    - grub
- include: tz.yml
  tags:
    - time
- include: network.yml
  tags:
    - network
- include: speedupboot.yml
  tags:
    - speedupboot
- include: fail2ban.yml
  tags:
    - ssh
    - security
#- include: selinux.yml
#  tags:
#    - selinux
#    - security
