---
- name: Install SELinux
  apt: name={{ item }} state=present
  with_items:
    - selinux-basics
    - selinux-policy-default
    - auditd
  register: selinux

- name: Activate SELinux
  command: selinux-activate
  when: selinux.changed

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: selinux.changed

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  when: selinux.changed

- name: Check policy
  command: check-selinux-installation
  when: selinux.changed
