---

- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - quota
    - quotatool

- name: Stop Quota if running
  command: quotaoff -av

- name: Create Quota-files
  command: quotacheck -vguma
  ignore_errors: yes

- name: Activate Quota
  command: quotaon -av

- name: Config Quota of Guest
  command: quotatool -u gast -b -q 10G -l 50G /data 

- name: Config grace period of Guest
  command: quotatool -u gast -b -t "2 hour" /data

